### ISSUE TITLE
RankUpper not working on latest sponge

### ISSUE THREAD

**Issue by Tencao** [FabioZumbi12/Sponge-RankUpper#21]
```
Server thread/ERROR
12/10/2017 22:38:18
[Sponge]: Error occurred while executing command 'ru check Jarebear45' for source EntityPlayerMP['Tencao'/22833, l='Aleria', x=-2635.64, y=71.00, z=939.53]: me.lucko.luckperms.sponge.service.model.SubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject

Console
12/10/2017 22:38:18
java.lang.ClassCastException: me.lucko.luckperms.sponge.service.model.SubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
at br.net.fabiozumbi12.rankupper.RUPermsAPI.getHighestGroup(RUPermsAPI.java:32) ~[RUPermsAPI.class:?]
at br.net.fabiozumbi12.rankupper.RUCommands.SendCheckMessage(RUCommands.java:280) ~[RUCommands.class:?]
at br.net.fabiozumbi12.rankupper.RUCommands.lambda$rankUpper$4(RUCommands.java:118) ~[RUCommands.class:?]
at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:181) ~[ChildCommandElementExecutor.class:1.12.2-2555-7.0.0-BETA-2764]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:360) ~[CommandSpec.class:1.12.2-2555-7.0.0-BETA-2764]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342) ~[SimpleDispatcher.class:1.12.2-2555-7.0.0-BETA-2764]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:321) [SpongeCommandManager.class:1.12.2-2555-7.0.0-BETA-2764]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-2555-7.0.0-BETA-2764]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkf000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.0.0-BETA-2764]
at net.minecraft.server.MinecraftServer.redirect$onRun$zil000(MinecraftServer.java:4008) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

Sponge version - 1.12.2-2555-7.0.0-BETA-2764
Minecraft - 1.12.2
Forge - 14.23.1.2559

**Comment by FabioZumbi12** [comment]
This is fixed on our latest dev build http://areaz12server.net.br:8080/job/RankUpper/
