### ISSUE TITLE
Can't use /Ru Check

### ISSUE THREAD

**Issue by zayonarts** [FabioZumbi12/Sponge-RankUpper#24]
I have an issue when i try to use /ru check : 

[14:30:33] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'ru check' for source EntityPlayerMP['Fmohican'/113570, l='World', x=-1222.90, y=207.00, z=-1925.44]: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
        at br.net.fabiozumbi12.rankupper.RUPermsAPI.getHighestGroup(RUPermsAPI.java:32) ~[RUPermsAPI.class:?]
        at br.net.fabiozumbi12.rankupper.RUConfig.checkRankup(RUConfig.java:346) ~[RUConfig.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.lambda$rankUpper$4(RUCommands.java:121) ~[RUCommands.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[14:31:17] [Server thread/INFO] [nucleus]: Fmohican ran the command: /ru check DeTeK
[14:31:32] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'ru check DeTeK' for source EntityPlayerMP['Fmohican'/113570, l='World', x=-1221.95, y=208.00, z=-1925.43]: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
        at br.net.fabiozumbi12.rankupper.RUPermsAPI.getHighestGroup(RUPermsAPI.java:32) ~[RUPermsAPI.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.SendCheckMessage(RUCommands.java:280) ~[RUCommands.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.lambda$rankUpper$4(RUCommands.java:118) ~[RUCommands.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[14:31:32] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 14859ms behind, skipping 297 tick(s)
[14:31:32] [Server thread/INFO] [nucleus]: Fmohican ran the command: /ru check DeTeK
[14:31:32] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'ru check DeTeK' for source EntityPlayerMP['Fmohican'/113570, l='World', x=-1222.16, y=208.00, z=-1925.43]: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
        at br.net.fabiozumbi12.rankupper.RUPermsAPI.getHighestGroup(RUPermsAPI.java:32) ~[RUPermsAPI.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.SendCheckMessage(RUCommands.java:280) ~[RUCommands.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.lambda$rankUpper$4(RUCommands.java:118) ~[RUCommands.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[14:31:42] [Server thread/INFO] [nucleus]: Fmohican ran the command: /ru check DeTeK
[14:31:42] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'ru check DeTeK' for source EntityPlayerMP['Fmohican'/113570, l='World', x=-1222.35, y=208.75, z=-1920.35]: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
        at br.net.fabiozumbi12.rankupper.RUPermsAPI.getHighestGroup(RUPermsAPI.java:32) ~[RUPermsAPI.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.SendCheckMessage(RUCommands.java:280) ~[RUCommands.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.lambda$rankUpper$4(RUCommands.java:118) ~[RUCommands.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[14:31:43] [Server thread/INFO] [nucleus]: Fmohican ran the command: /ru check DeTeK
[14:31:43] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'ru check DeTeK' for source EntityPlayerMP['Fmohican'/113570, l='World', x=-1222.10, y=208.75, z=-1920.44]: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
        at br.net.fabiozumbi12.rankupper.RUPermsAPI.getHighestGroup(RUPermsAPI.java:32) ~[RUPermsAPI.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.SendCheckMessage(RUCommands.java:280) ~[RUCommands.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.lambda$rankUpper$4(RUCommands.java:118) ~[RUCommands.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[14:31:43] [Server thread/INFO] [nucleus]: Fmohican ran the command: /ru check DeTeK
[14:31:43] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'ru check DeTeK' for source EntityPlayerMP['Fmohican'/113570, l='World', x=-1222.10, y=208.75, z=-1920.44]: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.LuckPermsSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
        at br.net.fabiozumbi12.rankupper.RUPermsAPI.getHighestGroup(RUPermsAPI.java:32) ~[RUPermsAPI.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.SendCheckMessage(RUCommands.java:280) ~[RUCommands.class:?]
        at br.net.fabiozumbi12.rankupper.RUCommands.lambda$rankUpper$4(RUCommands.java:118) ~[RUCommands.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-2944]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2944]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
![2018-03-02_14 32 41](https://user-images.githubusercontent.com/17950489/36899331-3db40aca-1e27-11e8-8893-365b604aa87c.png)

**Comment by FabioZumbi12** [comment]
You is using an old version of RankUpper. Download the latest from http://areaz12server.net.br:8080/job/RankUpper/
