### ISSUE TITLE
Error starting RankUpper

### ISSUE THREAD

**Issue by ghost** [FabioZumbi12/Sponge-RankUpper#29]
This error occurred when I updated for the last Sponge experimental version, API 8

> [18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]: java.lang.IllegalArgumentException: Configuration does not accept objects of type class br.net.fabiozumbi12.RankUpper.config.MainCategory
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at ninja.leaping.configurate.ScalarConfigValue.setValue(ScalarConfigValue.java:51)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at ninja.leaping.configurate.SimpleConfigurationNode.insertNewValue(SimpleConfigurationNode.java:311)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:276)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:87)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:33)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at ninja.leaping.configurate.SimpleConfigurationNode.storeDefault(SimpleConfigurationNode.java:117)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:200)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at br.net.fabiozumbi12.RankUpper.config.RUConfig.<init>(RUConfig.java:55)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at br.net.fabiozumbi12.RankUpper.RankUpper.onServerStart(RankUpper.java:118)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at org.spongepowered.common.event.listener.GameStartedServerEventListener_RankUpper_onServerStart51.handle(Unknown Source)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:420)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:233)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:246)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at java.lang.reflect.Method.invoke(Unknown Source)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at java.lang.reflect.Method.invoke(Unknown Source)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:807)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:301)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
[18:09:49] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:151]:  at java.lang.Thread.run(Unknown Source)
[18:09:49] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: RankUpper: [Error enabling RankUpper! Plugin Disabled.]

**Comment by FabioZumbi12** [comment]
Try the latext version from our jenkins https://host.areaz12server.net.br:8080/job/RankUpper/
