### ISSUE TITLE
[BUG] Plugin failed to load, version was "${projectversion}" instead of an int

### ISSUE THREAD

**Issue by AngryCarrot789** [FabioZumbi12/Sponge-RankUpper#50]
**Describe the bug**
I built the plugin from sources in this git repo, and I created the jar using the jar:jar maven action, but that jar gives me this exception:
```
[11:23:40] [Server thread/INFO] [minecraft/DedicatedServer]: RankUpper: [Init lang module...]
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]: java.lang.NumberFormatException: For input string: "${projectversion}"
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at java.lang.Integer.parseInt(Integer.java:569)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at java.lang.Integer.parseInt(Integer.java:615)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at br.net.fabiozumbi12.RankUpper.RULang.loadLang(RULang.java:76)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at br.net.fabiozumbi12.RankUpper.RULang.<init>(RULang.java:49)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at br.net.fabiozumbi12.RankUpper.RankUpper.onServerStart(RankUpper.java:128)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at org.spongepowered.common.event.listener.GameStartedServerEventListener_RankUpper_onServerStart16.handle(Unknown Source)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:255)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:363)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at java.lang.reflect.Method.invoke(Method.java:498)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at java.lang.reflect.Method.invoke(Method.java:498)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at net.minecraftforge.fml.common.LoadController.redirect$zza000$forgeImpl$PostEvent(LoadController.java:1068)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
[11:23:40] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.RankUpper.RankUpper:onServerStart:159]:  at java.lang.Thread.run(Thread.java:748)
[11:23:40] [Server thread/INFO] [minecraft/DedicatedServer]: RankUpper: [Error enabling RankUpper! Plugin Disabled.]
```

**To Reproduce**
1. Clone project repo and built using IntelliJ
2. Run the jar:jar maven action, and install the jar in your mods folder
3. Run the server and the exception occurs

**Expected behavior**
The plugin should load normally

**Server and plugins versions (please complete the following information):**
 - Server: Sponge 1.12.2
 - Plugin Version: 
 - Java Version: Java 8

**Comment by AngryCarrot789** [comment]
I forgot to edit the VersionData class, and `${projectversion}` is what was in that static string
